-- Zyro Hub Script for The Strongest Battleground
-- Author: Generated by AI (placeholder)
-- Version: 1.0
-- Description: A compact hub for loading techs, player modifications, map utilities, and settings.

-- ====================
-- Module Setup
-- ====================
local ZyroHub = {}
ZyroHub.Version = "1.0"
ZyroHub.TechList = {  -- Default techs with placeholder URLs (replace with real ones)
    {Name = "Supa Tech V2", URL = "https://pastebin.com/raw/placeholder_supa", Loaded = false},
    {Name = "Kai Tech", URL = "https://pastebin.com/raw/placeholder_kai", Loaded = false},
    {Name = "Freeze Tech", URL = "https://pastebin.com/raw/placeholder_freeze", Loaded = false},
    {Name = "Lethal Kiba", URL = "https://pastebin.com/raw/placeholder_kiba", Loaded = false},
}
ZyroHub.Player = game.Players.LocalPlayer
ZyroHub.Character = ZyroHub.Player.Character or ZyroHub.Player.CharacterAdded:Wait()
ZyroHub.Humanoid = ZyroHub.Character:WaitForChild("Humanoid")
ZyroHub.UIEnabled = false
ZyroHub.Keybind = Enum.KeyCode.RightShift  -- Default toggle key
ZyroHub.Theme = "Dark"  -- Default theme: Dark or Light
ZyroHub.AutoLoadTechs = false  -- Auto load on join
ZyroHub.Notifications = {}  -- For logs/notifications

-- ====================
-- UI Module
-- ====================
function ZyroHub:CreateUI()
    local ScreenGui = Instance.new("ScreenGui")
    ScreenGui.Name = "ZyroHubGui"
    ScreenGui.Parent = game.CoreGui  -- Use CoreGui for overlay
    ScreenGui.Enabled = false

    local MainFrame = Instance.new("Frame")
    MainFrame.Size = UDim2.new(0, 300, 0, 400)
    MainFrame.Position = UDim2.new(0.5, -150, 0.5, -200)
    MainFrame.BackgroundColor3 = (ZyroHub.Theme == "Dark") and Color3.fromRGB(30, 30, 30) or Color3.fromRGB(240, 240, 240)
    MainFrame.BorderSizePixel = 0
    MainFrame.Parent = ScreenGui

    local TitleLabel = Instance.new("TextLabel")
    TitleLabel.Size = UDim2.new(1, 0, 0, 30)
    TitleLabel.Text = "Zyro Hub - The Strongest Battleground"
    TitleLabel.BackgroundColor3 = Color3.fromRGB(50, 50, 50)
    TitleLabel.TextColor3 = Color3.fromRGB(255, 255, 255)
    TitleLabel.Parent = MainFrame

    -- Tabs
    local TabButtons = {}
    local Tabs = {"Tech Loader", "Player Options", "Map Utilities", "Settings"}
    local TabFrames = {}

    for i, tabName in ipairs(Tabs) do
        local TabButton = Instance.new("TextButton")
        TabButton.Size = UDim2.new(0.25, 0, 0, 30)
        TabButton.Position = UDim2.new((i-1)*0.25, 0, 0, 30)
        TabButton.Text = tabName
        TabButton.BackgroundColor3 = Color3.fromRGB(70, 70, 70)
        TabButton.TextColor3 = Color3.fromRGB(255, 255, 255)
        TabButton.Parent = MainFrame
        table.insert(TabButtons, TabButton)

        local TabFrame = Instance.new("Frame")
        TabFrame.Size = UDim2.new(1, 0, 1, -60)
        TabFrame.Position = UDim2.new(0, 0, 0, 60)
        TabFrame.BackgroundTransparency = 1
        TabFrame.Visible = (i == 1)
        TabFrame.Parent = MainFrame
        TabFrames[tabName] = TabFrame
    end

    -- Tab Switching
    for i, button in ipairs(TabButtons) do
        button.MouseButton1Click:Connect(function()
            for _, frame in pairs(TabFrames) do
                frame.Visible = false
            end
            TabFrames[Tabs[i]].Visible = true
        end)
    end

    -- Apply Theme
    function ZyroHub:ApplyTheme()
        MainFrame.BackgroundColor3 = (ZyroHub.Theme == "Dark") and Color3.fromRGB(30, 30, 30) or Color3.fromRGB(240, 240, 240)
        for _, button in ipairs(TabButtons) do
            button.BackgroundColor3 = (ZyroHub.Theme == "Dark") and Color3.fromRGB(70, 70, 70) or Color3.fromRGB(200, 200, 200)
            button.TextColor3 = (ZyroHub.Theme == "Dark") and Color3.fromRGB(255, 255, 255) or Color3.fromRGB(0, 0, 0)
        end
        -- Apply to other elements as needed
    end

    return ScreenGui, TabFrames
end

-- ====================
-- Tech Loader Module
-- ====================
function ZyroHub:SetupTechLoader(TabFrame)
    local SearchBox = Instance.new("TextBox")
    SearchBox.Size = UDim2.new(1, 0, 0, 30)
    SearchBox.Position = UDim2.new(0, 0, 0, 0)
    SearchBox.PlaceholderText = "Search Tech..."
    SearchBox.Parent = TabFrame

    local TechListFrame = Instance.new("ScrollingFrame")
    TechListFrame.Size = UDim2.new(1, 0, 1, -30)
    TechListFrame.Position = UDim2.new(0, 0, 0, 30)
    TechListFrame.Parent = TabFrame

    local UIListLayout = Instance.new("UIListLayout")
    UIListLayout.Parent = TechListFrame

    function ZyroHub:RefreshTechList(filter)
        for _, child in ipairs(TechListFrame:GetChildren()) do
            if child:IsA("TextButton") then child:Destroy() end
        end
        for _, tech in ipairs(ZyroHub.TechList) do
            if not filter or string.find(string.lower(tech.Name), string.lower(filter)) then
                local TechButton = Instance.new("TextButton")
                TechButton.Size = UDim2.new(1, 0, 0, 30)
                TechButton.Text = tech.Name .. (tech.Loaded and " (Loaded)" or "")
                TechButton.Parent = TechListFrame
                TechButton.MouseButton1Click:Connect(function()
                    ZyroHub:LoadTech(tech)
                end)
            end
        end
    end

    ZyroHub:RefreshTechList()

    SearchBox.FocusLost:Connect(function()
        ZyroHub:RefreshTechList(SearchBox.Text)
    end)

    -- Add New Tech Button (placeholder for input)
    local AddButton = Instance.new("TextButton")
    AddButton.Size = UDim2.new(1, 0, 0, 30)
    AddButton.Position = UDim2.new(0, 0, 1, -30)
    AddButton.Text = "Add New Tech (URL/Module)"
    AddButton.Parent = TabFrame
    AddButton.MouseButton1Click:Connect(function()
        -- Placeholder: Prompt for URL or name
        table.insert(ZyroHub.TechList, {Name = "New Tech", URL = "https://placeholder.com", Loaded = false})
        ZyroHub:RefreshTechList()
    end)

    -- Auto Load
    if ZyroHub.AutoLoadTechs then
        for _, tech in ipairs(ZyroHub.TechList) do
            ZyroHub:LoadTech(tech)
        end
    end
end

function ZyroHub:LoadTech(tech)
    if tech.Loaded then return end
    pcall(function()
        loadstring(game:HttpGet(tech.URL))()
        tech.Loaded = true
        ZyroHub:Notify("Loaded " .. tech.Name .. " successfully.")
    end)
    if not tech.Loaded then
        ZyroHub:Notify("Error loading " .. tech.Name)
    end
    ZyroHub:RefreshTechList()
end

-- ====================
-- Player Features Module
-- ====================
function ZyroHub:SetupPlayerOptions(TabFrame)
    local Features = {
        {Name = "Speed", Type = "Slider", Min = 16, Max = 100, Default = 16, Func = function(val) ZyroHub.Humanoid.WalkSpeed = val end},
        {Name = "Jump", Type = "Slider", Min = 50, Max = 200, Default = 50, Func = function(val) ZyroHub.Humanoid.JumpPower = val end},
        {Name = "No Fall Damage", Type = "Toggle", Func = function(state)
            if state then
                ZyroHub.Humanoid.StateChanged:Connect(function(_, new) if new == Enum.HumanoidStateType.FallingDown then ZyroHub.Humanoid:ChangeState(Enum.HumanoidStateType.GettingUp) end end)
            end
        end},
        {Name = "God Mode", Type = "Toggle", Func = function(state)
            if state then
                ZyroHub.Humanoid.HealthChanged:Connect(function(health) if health < ZyroHub.Humanoid.MaxHealth then ZyroHub.Humanoid.Health = ZyroHub.Humanoid.MaxHealth end end)
            end
        end},
        -- Add more features like Auto-Farm, ESP, etc. as placeholders
        {Name = "Auto Collect Items", Type = "Toggle", Func = function(state) -- Implement logic end},
        {Name = "Infinite Stamina", Type = "Toggle", Func = function(state) -- Implement logic end},
        {Name = "ESP", Type = "Toggle", Func = function(state) -- Use Highlight or BillboardGui end},
    }

    local yPos = 0
    for _, feature in ipairs(Features) do
        local Label = Instance.new("TextLabel")
        Label.Size = UDim2.new(0.5, 0, 0, 30)
        Label.Position = UDim2.new(0, 0, 0, yPos)
        Label.Text = feature.Name
        Label.Parent = TabFrame

        if feature.Type == "Slider" then
            local Slider = Instance.new("TextBox")  -- Placeholder slider
            Slider.Size = UDim2.new(0.5, 0, 0, 30)
            Slider.Position = UDim2.new(0.5, 0, 0, yPos)
            Slider.Text = tostring(feature.Default)
            Slider.FocusLost:Connect(function()
                local val = tonumber(Slider.Text) or feature.Default
                val = math.clamp(val, feature.Min, feature.Max)
                feature.Func(val)
            end)
            Slider.Parent = TabFrame
        elseif feature.Type == "Toggle" then
            local ToggleButton = Instance.new("TextButton")
            ToggleButton.Size = UDim2.new(0.5, 0, 0, 30)
            ToggleButton.Position = UDim2.new(0.5, 0, 0, yPos)
            ToggleButton.Text = "Off"
            local state = false
            ToggleButton.MouseButton1Click:Connect(function()
                state = not state
                ToggleButton.Text = state and "On" or "Off"
                feature.Func(state)
            end)
            ToggleButton.Parent = TabFrame
        end
        yPos = yPos + 30
    end
end

-- ====================
-- Map Utilities Module
-- ====================
function ZyroHub:SetupMapUtilities(TabFrame)
    -- Teleport buttons, etc.
    local Teleports = {
        {Name = "Spawn", Position = Vector3.new(0, 0, 0)},  -- Placeholder positions
        {Name = "Boss", Position = Vector3.new(100, 0, 100)},
    }

    local yPos = 0
    for _, tp in ipairs(Teleports) do
        local TpButton = Instance.new("TextButton")
        TpButton.Size = UDim2.new(1, 0, 0, 30)
        TpButton.Position = UDim2.new(0, 0, 0, yPos)
        TpButton.Text = "Teleport to " .. tp.Name
        TpButton.MouseButton1Click:Connect(function()
            ZyroHub.Character.HumanoidRootPart.CFrame = CFrame.new(tp.Position)
        end)
        TpButton.Parent = TabFrame
        yPos = yPos + 30
    end

    -- Add Map Info, Auto Farm, etc.
end

-- ====================
-- Settings Module
-- ====================
function ZyroHub:SetupSettings(TabFrame)
    -- Keybind
    local KeybindLabel = Instance.new("TextLabel")
    KeybindLabel.Size = UDim2.new(1, 0, 0, 30)
    KeybindLabel.Text = "Toggle Key: " .. ZyroHub.Keybind.Name
    KeybindLabel.Parent = TabFrame

    -- Theme Toggle
    local ThemeButton = Instance.new("TextButton")
    ThemeButton.Size = UDim2.new(1, 0, 0, 30)
    ThemeButton.Position = UDim2.new(0, 0, 0, 30)
    ThemeButton.Text = "Switch Theme: " .. ZyroHub.Theme
    ThemeButton.MouseButton1Click:Connect(function()
        ZyroHub.Theme = (ZyroHub.Theme == "Dark") and "Light" or "Dark"
        ZyroHub:ApplyTheme()
        ThemeButton.Text = "Switch Theme: " .. ZyroHub.Theme
    end)
    ThemeButton.Parent = TabFrame

    -- Auto Update Tech List (placeholder)
    -- Auto Load Toggle
    local AutoLoadToggle = Instance.new("TextButton")
    AutoLoadToggle.Size = UDim2.new(1, 0, 0, 30)
    AutoLoadToggle.Position = UDim2.new(0, 0, 0, 60)
    AutoLoadToggle.Text = "Auto Load Techs: " .. (ZyroHub.AutoLoadTechs and "On" or "Off")
    AutoLoadToggle.MouseButton1Click:Connect(function()
        ZyroHub.AutoLoadTechs = not ZyroHub.AutoLoadTechs
        AutoLoadToggle.Text = "Auto Load Techs: " .. (ZyroHub.AutoLoadTechs and "On" or "Off")
    end)
    AutoLoadToggle.Parent = TabFrame
end

-- ====================
-- Notification System
-- ====================
function ZyroHub:Notify(message)
    table.insert(ZyroHub.Notifications, message)
    -- Placeholder: Print to console or create toast UI
    print("[Zyro Hub] " .. message)
end

-- ====================
-- Initialization
-- ====================
local UIS = game:GetService("UserInputService")
local ScreenGui, TabFrames = ZyroHub:CreateUI()

ZyroHub:SetupTechLoader(TabFrames["Tech Loader"])
ZyroHub:SetupPlayerOptions(TabFrames["Player Options"])
ZyroHub:SetupMapUtilities(TabFrames["Map Utilities"])
ZyroHub:SetupSettings(TabFrames["Settings"])

UIS.InputBegan:Connect(function(input)
    if input.KeyCode == ZyroHub.Keybind then
        ZyroHub.UIEnabled = not ZyroHub.UIEnabled
        ScreenGui.Enabled = ZyroHub.UIEnabled
    end
end)

-- Handle Character Respawn
ZyroHub.Player.CharacterAdded:Connect(function(char)
    ZyroHub.Character = char
    ZyroHub.Humanoid = char:WaitForChild("Humanoid")
    -- Reapply active features
end)

-- Auto Load if enabled
if ZyroHub.AutoLoadTechs then
    for _, tech in ipairs(ZyroHub.TechList) do
        ZyroHub:LoadTech(tech)
    end
end

return ZyroHub
